/**
 * Stable platform permission contracts from docs/data/PERMISSION_CATALOG.md.
 *
 * Labels and role names are intentionally absent: callers authorize with these
 * immutable machine keys only.
 */
export const PLATFORM_PERMISSION_KEYS = Object.freeze([
  "workspace.read",
  "workspace.manage",
  "users.read",
  "users.manage",
  "roles.manage",
  "configuration.read",
  "configuration.manage",
  "approvals.read",
  "approvals.create",
  "integrations.read",
  "integrations.manage",
  "jobs.read",
  "jobs.manage",
  "audit.read",
  "inventory.read",
  "inventory.create",
  "inventory.update",
  "inventory.transition",
  "inventory.archive",
  "costs.read",
  "costs.create",
  "costs.reverse",
  "media.read",
  "media.create",
  "media.update",
  "media.archive",
  "listings.read",
  "listings.publish",
  "listings.unpublish",
  "listings.reconcile",
  "crm.read",
  "crm.create",
  "crm.update",
  "crm.assign",
  "deals.read",
  "deals.create",
  "deals.update",
  "deals.transition",
  "deals.cancel",
  "deals.close",
  "finance_applications.read",
  "finance_applications.create",
  "finance_applications.update",
  "payments.read",
  "payments.record",
  "payments.settle",
  "payments.reverse",
  "payments.refund",
  "documents.read",
  "documents.preview",
  "documents.generate_approved",
  "documents.print",
  "documents.upload_signed",
  "documents.mark_signed",
  "documents.void",
  "documents.void_signed",
  "documents.supersede",
  "formula.read",
  "formula.activate",
  "tax.read",
  "tax.activate",
  "template.read",
  "template.activate",
  "workflow.read",
  "workflow.activate",
  "numbering.read",
  "numbering.activate",
  "reports.read",
  "exports.read",
  "exports.run",
  "exports.run_sensitive",
  "identifiers.read_restricted",
  "identifiers.manage",
  "files.read_restricted",
  "support.access",
] as const);

export type PlatformPermissionKey = (typeof PLATFORM_PERMISSION_KEYS)[number];

const platformPermissionKeySet: ReadonlySet<string> = new Set(
  PLATFORM_PERMISSION_KEYS,
);

export function isPlatformPermissionKey(
  value: unknown,
): value is PlatformPermissionKey {
  return typeof value === "string" && platformPermissionKeySet.has(value);
}
