import { handleApplicationQueryRoute } from "@/lib/api/command-route";
import { createM4DownloadApplicationService } from "@/lib/api/postgrest";

interface RouteContext {
  readonly params: Promise<{ readonly id: string }>;
}

/** M4-EXP-AC-003..004: re-authorize exact generated bytes before signing. */
export async function GET(
  request: Request,
  context: RouteContext,
): Promise<Response> {
  const { id } = await context.params;
  return handleApplicationQueryRoute(request, {
    createService: createM4DownloadApplicationService,
    execute: (service, metadata) =>
      service.authorizeExportDownload(metadata, id),
  });
}
